VERSION="1.0.1"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GDNYNXBFPBKXDME6LY3UTVQ2JJC7HS62NJBATTNAEGU3MK5TMKOCLT75",
"GCZXK4XOSM5HKP7GAUD2N55RH7G6HJU4DDYIV4OCCYOOU67YRBVYTUSA"
]

[DOCUMENTATION]
ORG_NAME="Privacy Boys"
ORG_LOGO="https://vibrant-saha-04a28d.netlify.app/images/logo.png"
ORG_DESCRIPTION="Exploring Stellar Blockchain"

[[CURRENCIES]]
code="PRVC"
issuer="GDNYNXBFPBKXDME6LY3UTVQ2JJC7HS62NJBATTNAEGU3MK5TMKOCLT75"
display_decimals=7
name="Privacy Coin"
desc="Take your privacy to the next level."
conditions="550,000,000 issued"
image="https://vibrant-saha-04a28d.netlify.app/images/logo.png"

